Modules/Common/Config/config.php
Modules/Common/Database/Migrations/2020_11_10_205407_create_mu_containers_table.php
Modules/Common/Database/Migrations/2020_11_10_210517_create_mu_measure_unit_types_table.php
Modules/Common/Database/Migrations/2020_11_10_210636_create_mu_measure_units_table.php
Modules/Common/Database/Seeders/CommonDatabaseSeeder.php
Modules/Common/Database/Seeders/MuContainerSeeder.php
Modules/Common/Database/Seeders/MuMeasureUnitSeeder.php
Modules/Common/Database/Seeders/MuMeasureUnitTypeSeeder.php
Modules/Common/Entities/MuContainer.php
Modules/Common/Http/Controllers/CommonController.php
Modules/Common/Providers/CommonServiceProvider.php
Modules/Common/Providers/RouteServiceProvider.php
Modules/Common/Resources/views/index.blade.php
Modules/Common/Resources/views/layouts/master.blade.php
Modules/Common/Routes/api.php
Modules/Common/Routes/web.php
Modules/Common/composer.json
Modules/Common/module.json
Modules/Common/package.json
Modules/Common/vite.config.js
modules_statuses.json

feat: Add Common module
fix: The seeds were not working

feat: Add Common module

---

Modules/Common/Http/Controllers/MuContainerController.php
Modules/Common/Routes/api.php

feat: Make common/measure-unit/container endpoint

feat: Make common/measure-unit/container endpoint

---

Modules/Product/Database/Migrations/2020_09_01_160047_create_category_register_pl.php
Modules/Product/Database/Migrations/2020_09_01_160108_create_category_remove_pl.php
Modules/Product/Database/Migrations/2020_09_07_233850_create_marks_register_pl.php
Modules/Product/Database/Migrations/2020_09_07_233912_create_marks_remove_pl.php
Modules/Product/Database/Migrations/2020_09_18_015320_create_product_register_pl.php
Modules/Product/Database/Migrations/2020_09_18_214754_create_presentation_register_pl.php
Modules/Product/Database/Migrations/2020_09_22_002616_create_presentation_remove_pl.php
Modules/Product/Entities/Category.php
Modules/Product/Entities/Mark.php
Modules/Product/Entities/Presentation.php
Modules/Product/Entities/Product.php
Modules/Product/Http/Controllers/CategoryController.php
Modules/Product/Http/Controllers/MarkController.php
Modules/Product/Http/Controllers/PresentationController.php
Modules/Product/Http/Controllers/ProductController.php
Modules/Product/Routes/api.php

feat: (WIP) Migratios, Seeds, Models, Controllers & Routes

feat: (WIP) Migratios, Seeds, Models, Controllers & Routes

---

database/seeders/MenuSeeder.php
database/seeders/RoleSeeder.php

feat: Make structure of menu options

feat: Make structure of menu options

---

Modules/Product/Database/Migrations/2020_09_01_160047_create_category_register_pl.php
Modules/Product/Database/Migrations/2020_09_01_160108_create_category_remove_pl.php
Modules/Product/Database/Migrations/2020_09_07_233850_create_marks_register_pl.php
Modules/Product/Database/Migrations/2020_09_07_233912_create_marks_remove_pl.php
Modules/Product/Database/Migrations/2020_09_11_011010_create_presentation_deploy_pl.php
Modules/Product/Database/Migrations/2020_09_18_015320_create_product_register_pl.php
Modules/Product/Database/Migrations/2020_09_18_214754_create_presentation_register_pl.php
Modules/Product/Database/Migrations/2020_09_22_002616_create_presentation_remove_pl.php
Modules/Product/Entities/Category.php
Modules/Product/Http/Controllers/CategoryController.php

feat: CRUD of Category

---

Modules/Product/Entities/Mark.php
Modules/Product/Http/Controllers/MarkController.php
Modules/Product/Http/Services/Mark/IndexMarkService.php
Modules/Product/Http/Services/Mark/StoreMarkService.php
Modules/Product/Http/Services/Mark/UpdateMarkService.php
Modules/Product/Routes/api.php

feat: List Marks to CRUD

---

Modules/Product/Http/Controllers/MarkController.php
Modules/Product/Http/Resources/MarkResource.php
Modules/Product/Routes/api.php

feat: Return mark by markId

---

Modules/Product/Entities/Mark.php
Modules/Product/Http/Controllers/MarkController.php
Modules/Product/Http/Requests/Mark/StoreMarkRequest.php
Modules/Product/Http/Requests/Mark/UpdateMarkRequest.php
Modules/Product/Http/Services/Mark/IndexMarkService.php
Modules/Product/Http/Services/Mark/StoreMarkService.php
Modules/Product/Http/Services/Mark/UpdateMarkService.php
Modules/Product/Routes/api.php

feat: CRUD of Mark

---

Modules/Product/Http/Controllers/ProductController.php
Modules/Product/Http/Services/Product/IndexProductService.php
Modules/Product/Http/Services/Product/StoreProductService.php
Modules/Product/Http/Services/Product/UpdateProductService.php
Modules/Product/Routes/api.php

feat: List products to CRUD

---

Modules/Product/Entities/Product.php
Modules/Product/Http/Services/Product/IndexProductService.php

feat: Add category and mark to product list

feat: Add category and mark to product list

---

Modules/Product/Routes/api.php

refactor: Category routes

---

Modules/Product/Http/Controllers/MarkController.php
Modules/Product/Routes/api.php

feat: Show list of marks to fill select

feat: feat: Show list of marks to fill select

---

Modules/Common/Routes/api.php
Modules/Product/Http/Controllers/ProductController.php

feat: Show product by id

---

Modules/Product/Http/Controllers/ProductController.php

feat: Pass data to api to update product

feat: Pass data to api to update product

---

Modules/Product/Entities/Product.php
Modules/Product/Http/Controllers/ProductController.php
Modules/Product/Http/Requests/Product/StoreProductRequest.php
Modules/Product/Http/Requests/Product/UpdateProductRequest.php
Modules/Product/Http/Services/Product/IndexProductService.php
Modules/Product/Http/Services/Product/StoreProductService.php
Modules/Product/Http/Services/Product/UpdateProductService.php

feat: Insert and update product

feat: Insert and update product

---

Modules/Product/Http/Requests/Product/StoreProductRequest.php
Modules/Product/Http/Requests/Product/UpdateProductRequest.php

feat: Add validations

---

app/Exceptions/CustomException.php
app/Exceptions/ExceptionInstance.php
app/Exceptions/Handler.php
routes/api.php

feat: Custom exception handling

feat: Custom exception handling

---

Modules/Product/Http/Controllers/PresentationController.php
Modules/Product/Http/Controllers/ProductController.php
Modules/Product/Http/Requests/Presentation/StorePresentationRequest.php
Modules/Product/Http/Services/Presentation/StorePresentationService.php
Modules/Product/Http/Services/Product/StoreProductService.php
Modules/Product/Routes/api.php
app/Exceptions/Handler.php

feat: Validate and create a new presentation from the data received.

feat: Validate and create a new presentation from the data received.

---

Modules/Product/Http/Controllers/PresentationController.php
Modules/Product/Routes/api.php

feat: List product presentations.

feat: List product presentations

---

Modules/Product/Http/Controllers/PresentationController.php
Modules/Product/Routes/api.php

feat: Allow to remove a presentation from the ID sent from the frontend.

feat: Allow to remove a presentation from the ID sent from the frontend

---

Modules/Product/Database/Migrations/2020_08_31_150104_create_presentations_table.php
Modules/Product/Entities/Presentation.php

feat: Apply SoftDelete to Presentation.

feat: Apply SoftDelete to Presentation

---

Modules/Product/Http/Controllers/PresentationController.php
Modules/Product/Routes/api.php

feat: Create controller and route to upload presentation file.

feat: Create controller and route to upload presentation file

---

Modules/Product/Database/Migrations/2020_08_31_150104_create_presentations_table.php
Modules/Product/Http/Controllers/PresentationController.php
Modules/Product/Routes/api.php

fix: Create controller and route to upload presentation file.

fix: Create controller and route to upload presentation file

---

Modules/Product/Database/Migrations/2020_08_31_150029_create_products_table.php
Modules/Product/Entities/Presentation.php
Modules/Product/Entities/Product.php
Modules/Product/Http/Controllers/ProductController.php

feat: Apply SoftDelete to Product.

feat: Apply SoftDelete to Product

---

Modules/Product/Http/Controllers/PresentationController.php

fix: Controller to upload presentation file.

fix: Controller to upload presentation file

---

Modules/Article/Entities/Article.php
Modules/Article/Entities/ArticleDetail.php
Modules/Article/Http/Controllers/ArticleController.php
Modules/Article/Http/Controllers/ArticleDetailController.php
Modules/Article/Http/Requests/Article/StoreArticleRequest.php
Modules/Article/Http/Requests/Article/UpdateArticleRequest.php
Modules/Article/Http/Requests/ArticleDetail/StoreArticleDetailRequest.php
Modules/Article/Http/Requests/ArticleDetail/UpdateArticleDetailRequest.php
Modules/Article/Http/Resources/ArticleResource.php
Modules/Article/Http/Services/Article/IndexArticleService.php
Modules/Article/Http/Services/Article/StoreArticleService.php
Modules/Article/Http/Services/Article/UpdateArticleService.php
Modules/Article/Http/Services/ArticleDetail/StoreArticleDetailService.php
Modules/Article/Http/Services/ArticleDetail/UpdateArticleDetailService.php
Modules/Article/Routes/api.php
Modules/Article/Routes/apiArticle.php
Modules/Article/Routes/apiArticleDetail.php

feat: Article module scaffold.

feat: Article module scaffold

---

Modules/Article/Database/Factories/ArticleDetailFactory.php
Modules/Article/Database/Factories/ArticleFactory.php
Modules/Article/Database/Migrations/2021_01_06_204637_create_article_details_table.php
Modules/Article/Database/Seeders/ArticleDatabaseSeeder.php
Modules/Article/Entities/Article.php
Modules/Article/Entities/ArticleDetail.php

feat: Articles factories

---

Modules/Article/Http/Controllers/ArticleDetailController.php
Modules/Article/Repositories/ArticleDetailRepository.php
Modules/Product/Entities/Presentation.php
Modules/Product/Entities/Product.php

feat: Show Categories, Marks and Packaging of Articles.

feat: Show Categories, Marks and Packaging of Articles

---

Modules/Article/Database/Factories/ArticleDetailFactory.php
Modules/Article/Database/Seeders/ArticleDatabaseSeeder.php

chore: Articles details factory.

chore: Articles details factory

---

Modules/Product/Database/Migrations/2020_08_31_150029_create_products_table.php
Modules/Product/Database/Migrations/2020_08_31_150104_create_presentations_table.php
Modules/Product/Database/Seeders/PresentationsTableSeeder.php
Modules/Product/Database/Seeders/ProductsTableSeeder.php
Modules/Product/Entities/Product.php
Modules/Product/Http/Requests/Presentation/StorePresentationRequest.php
Modules/Product/Http/Requests/Presentation/UpdatePresentationRequest.php
Modules/Product/Http/Services/Presentation/StorePresentationService.php
Modules/Product/Http/Services/Presentation/UpdatePresentationService.php

refactor: Delete unnecessary fields.

refactor: Delete unnecessary fields

---

Modules/Product/Http/Controllers/PresentationController.php
Modules/Product/Routes/api.php

feat: Point to api

---

Modules/Product/Entities/Presentation.php
Modules/Product/Entities/Product.php
Modules/Product/Http/Controllers/PresentationController.php

feat: Show presentations in search table.

feat: Show presentations in search table

---

Modules/Product/Http/Controllers/PresentationController.php

feat: Pagination for the search presentations table.

feat: Pagination for the search presentations table

---

Modules/Product/Http/Controllers/PresentationController.php

feat: Search presentations to create articles.

feat: Search presentations to create articles

---

Modules/Product/Http/Controllers/PresentationController.php

feat: Control selected presentations.

feat: Control selected presentations

---

Modules/Article/Http/Controllers/ArticleDetailController.php

feat: Test the endpoint of registering article detail.

feat: Test the endpoint of registering article detail

---

Modules/Article/Http/Controllers/ArticleDetailController.php
Modules/Article/Http/Services/ArticleDetail/StoreArticleDetailService.php

feat: Insert articles details.

feat: Insert articles details

---

Modules/Article/Routes/api.php
Modules/Inventory/Database/Migrations/2020_12_07_195327_create_movements_table.php
Modules/Inventory/Database/Migrations/2020_12_07_195353_create_movement_details_table.php
Modules/Inventory/Entities/MovementDetail.php
Modules/Inventory/Routes/api.php

feat: Continue with Inventory module.

feat: Continue with Inventory module

---

Modules/Store/Database/Migrations/2020_12_07_195327_create_movements_table.php
Modules/Store/Database/Seeders/MovementDetailTableSeeder.php
Modules/Store/Database/Seeders/MovementTableSeeder.php
Modules/Store/Database/Seeders/StoreDatabaseSeeder.php
Modules/Store/Entities/Movement.php
Modules/Store/Entities/MovementDetail.php
README.md

feat: Migrations and seeds of the movement table.

feat: Migrations and seeds of the movement table

---

Modules/Store/Database/Seeders/MovementDetailTableSeeder.php
Modules/Store/Database/Seeders/StoreDatabaseSeeder.php
Modules/Store/Entities/MovementDetail.php

feat: Migrations and seeds of the movement detail table.

feat: Migrations and seeds of the movement detail table

---

Modules/Store/Http/Controllers/MovementController.php

feat: Return movement records.

feat: Return movement records

---

Modules/Store/Http/Controllers/MovementController.php
Modules/Store/Routes/api.php

feat: Separate data by type of movement.

feat: Separate data by type of movement

---

Modules/Store/Http/Controllers/MovementController.php
Modules/Store/Http/Resources/ArticleResource.php
Modules/Store/Http/Resources/MovementResource.php
Modules/Store/Routes/api.php

feat: Edit movement

---

Modules/Store/Routes/api.php

feat: Stock existence mock since the backend.

feat: Stock existence mock since the backend

---

Modules/Store/Actions/ExistenceAction.php
Modules/Store/Entities/Existence.php
Modules/Store/Routes/api.php

feat: Stock existence action since the backend.

feat: Stock existence action since the backend

---

Modules/Article/app/Http/Controllers/ArticleController.php

feat: Search articles to movement.

feat: Search articles to movement

---

Modules/Store/app/Entities/MovementDetail.php
Modules/Store/app/Http/Controllers/MovementController.php

feat: Save movement (main/details) in database.

feat: Save movement (main/details) in database

---

Modules/Store/app/Actions/ExistenceAction.php
Modules/Store/app/Models/AnnualClosing.php
Modules/Store/app/Models/DailyClosing.php
Modules/Store/app/Models/MonthlyClosing.php
Modules/Store/database/migrations/2024_09_16_184406_create_support_types_table.php
Modules/Store/database/migrations/2024_11_14_133356_create_daily_closings.php
Modules/Store/database/migrations/2024_11_14_141514_create_monthly_closings.php
Modules/Store/database/migrations/2024_11_14_141710_create_annual_closings.php
Modules/Store/database/seeders/SupportTypesSeeder.php
docs/closes.sql

feat: Review stored functions and views.

feat: Review stored functions and views

---

Modules/Store/app/Http/Services/Movement/IndexMovementService.php

Change the order of the query list.

Change the order of the query list

---

Modules/Store/database/seeders/MovementTableSeeder.php

fix: Change movement type that is different from 1.

fix: Change movement type that is different from 1

---

Modules/Store/app/Entities/DailyClosing.php
Modules/Store/app/Http/Controllers/DailyClosingController.php
Modules/Store/app/Http/Services/DailyClosing/IndexDailyClosingService.php
Modules/Store/database/migrations/2020_12_16_001660_create_view_clousure_mov_date_time_article.php
Modules/Store/database/migrations/2020_12_16_001665_create_view_closure_pre_insert_aux.php
Modules/Store/database/migrations/2020_12_16_001676_create_view_closure_pre_insert.php
Modules/Store/routes/api.php
database/seeders/MenuSeeder.php
docs/closes.sql

feat: (WIP) Daily closing

---

Modules/Store/database/migrations/2020_12_16_001676_create_view_existence_daily_closing.php
Modules/Store/database/migrations/2020_12_17_001676_create_function_daily_closing_valid_dates.php
Modules/Store/database/migrations/2020_12_18_001676_create_function_daily_closing_date_exists.php
Modules/Store/database/migrations/2020_12_19_001676_create_function_daily_closing_register.php
Modules/Store/database/migrations/2020_12_20_001676_create_function_daily_closing.php
docs/closes.sql

feat: Add missing functions and views of daily closing.

feat: Add missing functions and views of daily closing

---

Modules/Store/app/Http/Controllers/DailyClosingController.php
Modules/Store/app/Http/Services/DailyClosing/IndexDailyClosingService.php
Modules/Store/routes/api.php

feat: Show daily closing

---

Modules/Store/app/Http/Controllers/DailyClosingController.php

fix: Show daily closing

---

docs/closes.sql

docs: Designing views to display stock

docs: Designing views to display stock

---

docs/closes.sql

feat: View stocks by accumulated plus unclosed movements.

feat: View stocks by accumulated plus unclosed movements

---

Modules/Store/app/Actions/ExistenceAction.php

feat: Resource stocks by accumulated plus unclosed movements.

feat: Resource stocks by accumulated plus unclosed movements

---

database/seeders/MenuSeeder.php
docs/closes.sql

docs: Design consult history of daily closings.

docs: Design consult history of daily closings

---

docs/closes.sql

docs: Improve query of historical design of daily closings.

docs: Improve query of historical design of daily closings

---

Modules/Store/app/Http/Controllers/DailyClosingController.php
Modules/Store/database/migrations/2020_12_15_231004_create_close_days_table.php
Modules/Store/database/migrations/2020_12_19_001676_create_function_daily_closing_register.php

feat: Add cumulative field to daily closing table.

feat: Add cumulative field to daily closing table

---

Modules/Store/database/migrations/2024_12_26_174239_create_sub_warehouses_table.php
Modules/Store/database/seeders/StoreDatabaseSeeder.php
Modules/Store/database/seeders/SubWarehouseSeeder.php

feat: SubWarehouse migrate and seed.

feat: SubWarehouse migrate and seed

---

Modules/Store/app/Entities/SubWarehouse.php
Modules/Store/app/Http/Controllers/SubWarehouseController.php
Modules/Store/app/Http/Requests/SubWarehouse/StoreSubWarehouseRequest.php
Modules/Store/app/Http/Requests/SubWarehouse/UpdateSubWarehouseRequest.php
Modules/Store/app/Http/Resources/SubWarehouseResource.php
Modules/Store/app/Http/Services/SubWarehouse/IndexSubWarehouseService.php
Modules/Store/app/Http/Services/SubWarehouse/StoreSubWarehouseService.php
Modules/Store/app/Http/Services/SubWarehouse/UpdateSubWarehouseService.php
Modules/Store/routes/api.php
database/seeders/MenuSeeder.php
database/seeders/RoleSeeder.php

feat: SubWarehouse crud

---

Modules/Store/app/Http/Requests/SubWarehouse/StoreSubWarehouseRequest.php
Modules/Store/app/Http/Requests/SubWarehouse/UpdateSubWarehouseRequest.php
Modules/Store/app/Http/Services/SubWarehouse/StoreSubWarehouseService.php
Modules/Store/app/Http/Services/SubWarehouse/UpdateSubWarehouseService.php

feat: Insert sub warehouses with uuid and not overwrite it with the update.

feat: Insert sub warehouses with uuid and not overwrite it with the update

---

Modules/Store/app/Http/Services/Movement/StoreMovementService.php
Modules/Store/database/migrations/2020_12_07_195327_create_movements_table.php
Modules/Store/database/seeders/MovementDetailTableSeeder.php
Modules/Store/database/seeders/MovementTableSeeder.php
Modules/Store/database/seeders/StoreDatabaseSeeder.php
docs/uuid_store.sql

feat: Save store_uuid at movements table.

feat: Save store_uuid at movements table

---

Modules/Store/app/Http/Controllers/MovementDetailController.php
Modules/Store/routes/api.php

feat: Create endpoint to get movement details by number.

feat: Create endpoint to get movement details by number

---

Modules/Store/app/Http/Controllers/MovementDetailController.php

feat: Validate type of movement before returning its details.

feat: Validate type of movement before returning its details

---

Modules/Common/database/seeders/MuContainerSeeder.php

chore: Add record Ream to table in Common database packaging.

chore: Add record Ream to table in Common database packaging

---

database/seeders/MenuSeeder.php

fix: Menu titles

---

Modules/Store/app/Actions/ExistenceAction.php
Modules/Store/routes/api.php

feat: Add pagination, search and sort to the stock datagrid.

feat: Add pagination, search and sort to the stock datagrid
